"""Parser registry."""

from __future__ import annotations

from . import (
    ai_code_flows,
    ai_agents,
    bot_configs,
    browser_extensions,
    cloud_credentials,
    docker,
    env_files,
    generic_config,
    github_actions,
    gitlab_ci,
    helm,
    iac_extra,
    kubernetes,
    mcp_configs,
    mcp_supply_chain,
    modern_saas,
    oauth_configs,
    package_json,
    package_registry,
    prompt_artifacts,
    rag_configs,
    python_requirements,
    terraform,
    terraform_state,
    webhooks,
)

PARSERS = [
    env_files,
    generic_config,
    github_actions,
    gitlab_ci,
    docker,
    terraform,
    terraform_state,
    helm,
    iac_extra,
    kubernetes,
    package_json,
    package_registry,
    oauth_configs,
    cloud_credentials,
    browser_extensions,
    prompt_artifacts,
    ai_agents,
    bot_configs,
    mcp_configs,
    mcp_supply_chain,
    rag_configs,
    ai_code_flows,
    modern_saas,
    webhooks,
    python_requirements,
]
