"""SQLite-backed parser output cache for incremental scans.

The cache key is `sha256(file content) + parser registry version`, so a file
hits the cache as long as its content and the parser implementations both
match the previous run. When a parser module bumps its `__version__`, every
cache entry generated by the prior version is automatically invalidated.

Cached signals are stored independent of file path so they can be reused
across rename / move (the path is rewritten back in on retrieval).
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from greynoc_nhi.masking import mask_secret, redact_inline_secret
from greynoc_nhi.utils import RAW_SECRET_MARKER_RE, assert_no_raw_secret_markers, chmod_private_dir, chmod_sqlite_sidecars

SENSITIVE_SIGNAL_KEYS = {"secret_value"}
SENSITIVE_TEXT_KEYS = {"evidence", "raw_reference", "context_store"}

# Bump whenever the disk-sanitization rules (masking.redact_inline_secret /
# sanitize_signal_for_disk) change. The value is folded into the cache key so
# rows sanitized under old rules are automatically invalidated instead of
# being re-sanitized on every hit.
SANITIZER_VERSION = 1

CACHE_SCHEMA = """
    CREATE TABLE IF NOT EXISTS parser_cache (
        cache_key TEXT PRIMARY KEY,
        parser_version TEXT NOT NULL,
        signals_json TEXT NOT NULL,
        cached_at TEXT NOT NULL
    );
"""


def parser_version_string(parsers: Iterable[Any]) -> str:
    """Produce a deterministic version-fingerprint for the parser registry."""
    parts: list[str] = []
    for parser in parsers:
        name = getattr(parser, "__name__", repr(parser))
        version = getattr(parser, "__version__", 0)
        parts.append(f"{name}={version}")
    return ";".join(sorted(parts))


def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def _make_key(content_sha: str, parser_version: str, dispatch: str = "") -> str:
    """Build the cache key.

    `dispatch` identifies WHICH parsers ran for the path (should_parse is
    path-dependent); without it, identical content under differently-gated
    filenames would collide and drop or misattribute name-gated findings.
    SANITIZER_VERSION invalidates rows written under older sanitization rules.
    """
    raw = f"{content_sha}|{parser_version}|{dispatch}|s{SANITIZER_VERSION}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def sanitize_signal_for_disk(signal: dict[str, Any]) -> dict[str, Any]:
    """Return a cache-safe signal copy with raw secret fields removed."""
    clean = dict(signal)
    secret_value = clean.get("secret_value")
    for key in SENSITIVE_TEXT_KEYS:
        if key in clean:
            clean[key] = _sanitize_signal_text(clean[key], secret_value)
    for key in SENSITIVE_SIGNAL_KEYS:
        clean.pop(key, None)
    return clean


def _sanitize_signal_text(value: Any, secret_value: Any | None) -> Any:
    if isinstance(value, list):
        return [_sanitize_signal_text(item, secret_value) for item in value]
    if isinstance(value, dict):
        return {key: _sanitize_signal_text(item, secret_value) for key, item in value.items()}
    if value is None:
        return None
    text = str(value)
    if secret_value:
        text = text.replace(str(secret_value), mask_secret(str(secret_value), include_fingerprint=False))
    return redact_inline_secret(text)


def sanitize_signals_for_disk(signals: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return cache-safe copies of parser signals."""
    return [sanitize_signal_for_disk(signal) for signal in signals]


class ParserCache:
    """Thin SQLite cache for parser-produced signal lists."""

    def __init__(self, db_path: str | Path | None) -> None:
        self.db_path = Path(db_path) if db_path else None
        self._conn: sqlite3.Connection | None = None
        if self.db_path is not None:
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            chmod_private_dir(self.db_path.parent)
            with self._connect() as conn:
                conn.executescript(CACHE_SCHEMA)
            chmod_sqlite_sidecars(self.db_path)

    def enabled(self) -> bool:
        return self.db_path is not None

    def _connect(self) -> sqlite3.Connection:
        """Return the persistent connection, creating it lazily.

        One connection (with its two PRAGMAs) is reused for every get/put/
        stats/clear instead of paying a connection open + WAL negotiation per
        operation. The scan loop is single-threaded, so sqlite3's default
        check_same_thread stays valid.
        """
        assert self.db_path is not None
        if self._conn is None:
            conn = sqlite3.connect(self.db_path, timeout=10)
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA synchronous=NORMAL")
            self._conn = conn
        return self._conn

    def close(self) -> None:
        """Close the persistent connection and re-apply sidecar permissions."""
        if self._conn is not None:
            try:
                self._conn.close()
            except sqlite3.Error:
                pass
            self._conn = None
        if self.db_path is not None:
            chmod_sqlite_sidecars(self.db_path)

    def get(
        self,
        content_sha: str,
        parser_version: str,
        *,
        dispatch: str = "",
    ) -> list[dict[str, Any]] | None:
        if not self.enabled():
            return None
        key = _make_key(content_sha, parser_version, dispatch)
        try:
            with self._connect() as conn:
                row = conn.execute(
                    "SELECT signals_json FROM parser_cache WHERE cache_key = ? AND parser_version = ?",
                    (key, parser_version),
                ).fetchone()
        except sqlite3.OperationalError:
            return None
        if row is None:
            return None
        raw_json = row[0]
        try:
            parsed = json.loads(raw_json)
        except (TypeError, ValueError):
            return None
        if not isinstance(parsed, list):
            return None
        # Rows are sanitized and marker-asserted at write time, and the cache
        # key embeds SANITIZER_VERSION, so a cheap screen over the raw JSON is
        # enough; only legacy/tampered rows pay the full re-sanitize + rewrite.
        if RAW_SECRET_MARKER_RE.search(raw_json) or '"secret_value"' in raw_json:
            safe = sanitize_signals_for_disk(parsed)
            if safe != parsed:
                self.put(content_sha, parser_version, safe, dispatch=dispatch)
            return safe
        return parsed

    def put(
        self,
        content_sha: str,
        parser_version: str,
        signals: list[dict[str, Any]],
        *,
        dispatch: str = "",
    ) -> None:
        if not self.enabled():
            return
        key = _make_key(content_sha, parser_version, dispatch)
        cached_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        safe_signals = sanitize_signals_for_disk(signals)
        assert_no_raw_secret_markers(safe_signals)
        try:
            with self._connect() as conn:
                conn.execute(
                    "INSERT OR REPLACE INTO parser_cache (cache_key, parser_version, signals_json, cached_at) VALUES (?, ?, ?, ?)",
                    (key, parser_version, json.dumps(safe_signals), cached_at),
                )
        except sqlite3.OperationalError:
            return

    def clear(self) -> None:
        if not self.enabled():
            return
        try:
            with self._connect() as conn:
                conn.execute("DELETE FROM parser_cache")
        except sqlite3.OperationalError:
            return

    def stats(self) -> dict[str, int]:
        if not self.enabled():
            return {"entries": 0}
        try:
            with self._connect() as conn:
                row = conn.execute("SELECT COUNT(*) FROM parser_cache").fetchone()
        except sqlite3.OperationalError:
            return {"entries": 0}
        return {"entries": int(row[0] if row else 0)}


def rewrite_file_path(signals: list[dict[str, Any]], new_path: str) -> list[dict[str, Any]]:
    """Return a copy of `signals` with the given file_path substituted in."""
    rewritten: list[dict[str, Any]] = []
    for signal in signals:
        cloned = dict(signal)
        cloned["file_path"] = new_path
        rewritten.append(cloned)
    return rewritten
