"""SQLite-backed parser output cache for incremental scans.

The cache key is `sha256(file content) + parser registry version`, so a file
hits the cache as long as its content and the parser implementations both
match the previous run. When a parser module bumps its `__version__`, every
cache entry generated by the prior version is automatically invalidated.

Cached signals are stored independent of file path so they can be reused
across rename / move (the path is rewritten back in on retrieval).
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

CACHE_SCHEMA = """
    CREATE TABLE IF NOT EXISTS parser_cache (
        cache_key TEXT PRIMARY KEY,
        parser_version TEXT NOT NULL,
        signals_json TEXT NOT NULL,
        cached_at TEXT NOT NULL
    );
"""


def parser_version_string(parsers: Iterable[Any]) -> str:
    """Produce a deterministic version-fingerprint for the parser registry."""
    parts: list[str] = []
    for parser in parsers:
        name = getattr(parser, "__name__", repr(parser))
        version = getattr(parser, "__version__", 0)
        parts.append(f"{name}={version}")
    return ";".join(sorted(parts))


def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def _make_key(content_sha: str, parser_version: str) -> str:
    return hashlib.sha256(f"{content_sha}|{parser_version}".encode("utf-8")).hexdigest()


class ParserCache:
    """Thin SQLite cache for parser-produced signal lists."""

    def __init__(self, db_path: str | Path | None) -> None:
        self.db_path = Path(db_path) if db_path else None
        if self.db_path is not None:
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            with self._connect() as conn:
                conn.executescript(CACHE_SCHEMA)

    def enabled(self) -> bool:
        return self.db_path is not None

    def _connect(self) -> sqlite3.Connection:
        assert self.db_path is not None
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        return conn

    def get(self, content_sha: str, parser_version: str) -> list[dict[str, Any]] | None:
        if not self.enabled():
            return None
        key = _make_key(content_sha, parser_version)
        try:
            with self._connect() as conn:
                row = conn.execute(
                    "SELECT signals_json FROM parser_cache WHERE cache_key = ? AND parser_version = ?",
                    (key, parser_version),
                ).fetchone()
        except sqlite3.OperationalError:
            return None
        if row is None:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None

    def put(self, content_sha: str, parser_version: str, signals: list[dict[str, Any]]) -> None:
        if not self.enabled():
            return
        key = _make_key(content_sha, parser_version)
        cached_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        try:
            with self._connect() as conn:
                conn.execute(
                    "INSERT OR REPLACE INTO parser_cache (cache_key, parser_version, signals_json, cached_at) VALUES (?, ?, ?, ?)",
                    (key, parser_version, json.dumps(signals), cached_at),
                )
        except sqlite3.OperationalError:
            return

    def clear(self) -> None:
        if not self.enabled():
            return
        try:
            with self._connect() as conn:
                conn.execute("DELETE FROM parser_cache")
        except sqlite3.OperationalError:
            return

    def stats(self) -> dict[str, int]:
        if not self.enabled():
            return {"entries": 0}
        try:
            with self._connect() as conn:
                row = conn.execute("SELECT COUNT(*) FROM parser_cache").fetchone()
        except sqlite3.OperationalError:
            return {"entries": 0}
        return {"entries": int(row[0] if row else 0)}


def rewrite_file_path(signals: list[dict[str, Any]], new_path: str) -> list[dict[str, Any]]:
    """Return a copy of `signals` with the given file_path substituted in."""
    rewritten: list[dict[str, Any]] = []
    for signal in signals:
        cloned = dict(signal)
        cloned["file_path"] = new_path
        rewritten.append(cloned)
    return rewritten
